language: java

jdk:
- oraclejdk8

branches:
  only:
    - master

before_install:
 - chmod +x gradlew

install:
- ./gradlew setupCIWorkspace

script:
- ./gradlew build

after_success:
- chmod +x curse_upload
- ./curse_upload
